POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "ikd",
    "password": "ikd"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "ikd",
   "email": "ikd@mail.fr",
   "password": "ikd"
}